### PR TITLE
Add support for Terraform 0.13

### PR DESCRIPTION
**Pull request by ianstanton**
- Bump release tags to `2.0.x`
- Update README with relevant versions
- Bump default Astronomer version to `0.16.12`
- Bump default EKS version to `1.18`
- Add necessary changes for terraform 0.13 support
- Related to https://github.com/astronomer/issues/issues/1910

### CODE REVIEW

**Comment by ianstanton** [comment]
My only concern is the pipeline failed multiple times due to timeout. I'm not sure if the root of this timeout was from something on our end or the AWS side of things.

**Comment by danielhoherd** [comment]
Oh, interesting... we can't not squash-and-merge here, because it's not enabled for the repo.

**Comment by danielhoherd** [comment]
> My only concern is the pipeline failed multiple times due to timeout. I'm not sure if the root of this timeout was from something on our end or the AWS side of things.

Timeouts are a known issue for us in testing. There is an issue to address this. astronomer/issues#2290

**Comment by danielhoherd** [comment]
The step that is timing out is [the destroy step](https://app.circleci.com/pipelines/github/astronomer/terraform-aws-astronomer-enterprise/29/workflows/aa783042-9b5d-44fd-afca-38d5e3a42154/jobs/70), so at least it's just CI or Terraform that is not working well, not this module.

**Review by danielhoherd — APPROVED** [review]

**Pull request merged**
