### PR TITLE
Bump astronomer version

### PR DESCRIPTION
**Pull request by ianstanton**
- Bump `terraform-kubernetes-astronomer` module to `1.1.88`
- Bump astronomer version to `0.12.1-rc.2` (to be changed)
- Related to astronomer/issues#1001
- CI will fail due to `postgresqlEnabled: true`
```
Error: rpc error: code = Unknown desc = release astronomer failed: secrets "astronomer-bootstrap" already exists
```
- This should pass once we update the astronomer version to a later release

### CODE REVIEW

**Comment by ianstanton** [comment]
@vparekh94 @sjmiller609 I bumped this to `v0.12.0` for now. We can bump again when `v0.12.1` is out.

**Comment by vparekh94** [comment]
perf! @sjmiller609 can you merge when you get a sec

**Comment by sjmiller609** [comment]
> perf! @sjmiller609 can you merge when you get a sec

dont' want to wait on 0.12.1? 0.12.0 has some bugs

**Comment by sjmiller609** [comment]
I leave the call up to @ianstanton but I think it's best to include the versions of Astronomer we want to support / are most confident in for this terraform module. if people use it with 0.12.0 then you will have to go upgrade them.

**Pull request merged**
