### PR TITLE
Guidance on using external cert and multiAZ Aurora

### PR DESCRIPTION
**Pull request by vparekh94**

### CODE REVIEW

**Comment by ianstanton** [comment]
Waiting for the two other PRs to merge before merging this one

**Comment by sjmiller609** [comment]
nice work thank you! yeah I agree to get the variables in at the same time as these docs

**Comment by ianstanton** [comment]
@sjmiller609 when that time comes are you able to skip the CI build for this one?

**Comment by sjmiller609** [comment]
> @sjmiller609 when that time comes are you able to skip the CI build for this one?

I would rather wait for drone to simmer down. when we merge, the CI will run again and the badge on the repository will show failed if the pipeline fails. that's bad optics

**Comment by sjmiller609** [comment]
I want to make sure this stays green: 
image

**Comment by ianstanton** [comment]
Closing, solved by https://github.com/astronomer/terraform-aws-astronomer-enterprise/pull/29

**Pull request closed without merging**
